spring:
  application:
    name: MyOrder
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: PBattistella2024
    url: jdbc:postgresql://localhost:5432/myorder_db
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: postgresql
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  springdoc:
    api-docs:
      path: /api-docs
    pathsToMatch:
      - /api/**
    swagger-ui:
      use-root-path: true
